name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      SERVER_PORT: ${{ secrets.PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
      SENS_SERVICE_ID: ${{ secrets.SENS_SERVICE_ID }}
      SENS_ACCESS_KEY: ${{ secrets.SENS_ACCESS_KEY }}
      SENS_REFRESH_KEY: ${{ secrets.SENS_SECRET_KEY }}
      SENS_PHONE: ${{ secrets.SENS_PHONE }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      S3_NAME: ${{ secrets.S3_NAME }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_ACCESS: ${{ secrets.S3_ACCESS }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      EDITOR_ID: ${{ secrets.EDITOR_ID }}
      EDITOR_PASSWORD: ${{ secrets.EDITOR_PASSWORD }}
    strategy:
      matrix:
        node-version: [10.19.0]
    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: build image
        run: docker build -t seungbin9850/shareup .

      - name: publish docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: seungbin9850/shareup
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
